const http=require('http'),https=require('https'),fs=require('fs'),path=require('path'),store=require('./lib/store');
const PORT=process.env.PORT||3000,PUBLIC=path.join(__dirname,'public');const MIME={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml'};
const seed=[{id:'case-1',title:'Interface choreography study',question:'How do repeated visual cues establish sequence and intent?',createdAt:'2026-09-09T05:48:00Z'}];const state=()=>store.read('carmen',null)||{investigations:seed,evidence:[],leads:[]};const save=x=>store.write('carmen',x);const id=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;
function request(url,limit=350000,extraHeaders={}){return new Promise((resolve,reject)=>{const lib=url.startsWith('https')?https:http;const r=lib.get(url,{headers:{...{'User-Agent':'Mozilla/5.0 Carmen/1.0','Accept':'text/html,application/xhtml+xml,image/avif,image/webp,*/*'},...extraHeaders}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location)return resolve(request(new URL(res.headers.location,url).href,limit,extraHeaders));let size=0,b=[];res.on('data',c=>{size+=c.length;b.push(c);if(size>limit)res.destroy()});let done=false;const finish=()=>{if(!done){done=true;resolve({status:res.statusCode,headers:res.headers,body:Buffer.concat(b).toString()})}};res.on('end',finish);res.on('close',finish)});r.setTimeout(3000,()=>r.destroy(new Error('Timed out')));r.on('error',reject)})}
const strip=s=>(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&#39;/g,"'").trim();const tag=(html,re)=>{const m=html.match(re);return m?strip(m[1]):''};
const providers={
  brave:{
    name:'Brave Search API',
    keyEnv:'BRAVE_SEARCH_API_KEY',
    maxCount:20,
    async run(q,mode,offset,count){const key=process.env[this.keyEnv];if(!key)throw new Error('BRAVE_SEARCH_API_KEY is not configured');let query=q;if(mode==='Reddit')query=`site:reddit.com ${q}`;if(mode==='Video')query=`${q} video`;if(mode==='Images')query=`${q} images`;const params=new URLSearchParams({q:query,count:String(Math.min(count,this.maxCount)),offset:String(offset),safesearch:'moderate',spellcheck:'true',uiLang:'en-US'});const r=await request(`https://api.search.brave.com/res/v1/web/search?${params}`,65536,{headers:{'Accept':'application/json','Accept-Encoding':'gzip','X-Subscription-Token':key}});let j;try{j=JSON.parse(r.body)}catch{throw new Error('Brave Search API returned non-JSON response')};if(j.type!=='search'||!Array.isArray(j.web?.results))throw new Error('Brave Search API returned an unexpected payload');const items=j.web.results.map((x,i)=>({title:x.title||'',url:x.url||'',description:x.description||'',source:x.profile?.name||new URL(x.url).hostname,thumbnail:x.thumbnail||'',age:x.age||'',relevance:offset+i<3?'Strong match':offset+i<7?'Possible match':'Weak / uncertain',why:`Matches "${q}" in the Brave search index.`,query,mode,discoveredAt:new Date().toISOString()})).filter(x=>x.url&&x.title);return {results:items,hasMore:(j.web?.results.length||0)>=Math.min(count,this.maxCount)}}
  },
  bing:{
    name:'Bing RSS (fallback)',
    async run(q,mode,offset,count){let query=q;if(mode==='Reddit')query=`site:reddit.com ${q}`;if(mode==='Video')query=`${q} video`;if(mode==='Images')query=`${q} images`;const r=await request(`https://www.bing.com/search?q=${encodeURIComponent(query)}&format=rss&count=50`);const items=[...r.body.matchAll(/<item>([\s\S]*?)<\/item>/g)].map(m=>({title:tag(m[1],/<title>([\s\S]*?)<\/title>/),url:tag(m[1],/<link>([\s\S]*?)<\/link>/),description:tag(m[1],/<description>([\s\S]*?)<\/description>/)})).filter(x=>x.url&&x.title).slice(offset,offset+count).map((x,i)=>{let source='Web';try{source=new URL(x.url).hostname}catch{}return {...x,source,relevance:offset+i<3?'Strong match':offset+i<7?'Possible match':'Weak / uncertain',why:`Matches "${q}" in the public search index.`,query,mode,discoveredAt:new Date().toISOString()}});return {results:items,hasMore:items.length>=count}}
  }
};
function getProvider(){const p=(process.env.SEARCH_PROVIDER||'brave').toLowerCase();return providers[p]||providers.brave}
async function search(q,mode,offset=0,count=10){const p=getProvider();const r=await p.run(q,mode,offset,count);return {query,mode,offset,results:r.results,hasMore:r.hasMore,provider:p.name}}
function discoveryHealth(){return Object.fromEntries(Object.entries(providers).map(([k,v])=>[k,{name:v.name,configured:!!(process.env[v.keyEnv||''])}]))}
function abs(src,base){try{return new URL(src,base).href}catch{return ''}}async function inspect(url){const r=await request(url);const html=r.body||'',title=tag(html,/<title[^>]*>([\s\S]*?)<\/title>/i)||tag(html,/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)/i);const desc=tag(html,/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']+)/i);const og=tag(html,/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/i);const imgs=[...html.matchAll(/<img[^>]+src=["']([^"']+)["']/gi)].map(x=>abs(x[1],url)).filter(Boolean);const visuals=[...new Set([og&&abs(og,url),...imgs] .filter(Boolean))].slice(0,1);const checked=await Promise.all(visuals.map(async asset=>{try{const x=await request(asset,10000);return {url:asset,retrieved:x.status>=200&&x.status<300&&/^image\//.test(x.headers['content-type']||''),status:x.status}}catch{return {url:asset,retrieved:false,status:0}}}));return {url,title,description:desc,site:new URL(url).hostname,status:r.status,access:r.status===200?'Publicly accessible':r.status===401||r.status===403?'Blocked or login required':'Inaccessible',metadata:{keywords:tag(html,/<meta[^>]+name=["']keywords["'][^>]+content=["']([^"']+)/i),author:tag(html,/<meta[^>]+name=["']author["'][^>]+content=["']([^"']+)/i)},visuals:checked,media:{video:/<video|<iframe/i.test(html),audio:/<audio/i.test(html),images:checked.length}}}
function analysisFor(x){const visual=!!x.image;return {observations:visual?'A visual asset was retrieved or supplied and is preserved as raw visual evidence. Carmen does not infer details not established by the image itself.':'No visual evidence available. Source metadata is not a direct visual observation.',objects:visual?'Retrieved visual evidence is available for inspection.':`Source type: ${x.sourceType}.`,inferences:'Source context may suggest a research direction. This remains suspected, not established.',signature:'Structural signature pending comparison. Confidence: low.',unknowns:'Object identities, relationships, sequence, and recurrence are not established by metadata alone.'}}
const routes={'GET /health':(q,s)=>json(s,{status:'ok',uptime:process.uptime(),discovery:discoveryHealth()}),'GET /api/state':(q,s)=>json(s,state()),'GET /api/search':async(q,s)=>{const u=new URL(q.url,'http://x');try{json(s,await search(u.searchParams.get('q')||'',u.searchParams.get('mode')||'All',+u.searchParams.get('offset')||0,+u.searchParams.get('count')||10))}catch(e){json(s,{error:'Public search provider failed: '+e.message},502)}},'POST /api/inspect':async(q,s)=>{try{json(s,await inspect((await body(q)).url))}catch(e){json(s,{error:'Source inspection failed: '+e.message},502)}},'POST /api/investigations':async(q,s)=>{const b=await body(q),d=state(),x={id:id('case'),title:b.title||'Untitled investigation',question:b.question||'',createdAt:new Date().toISOString()};d.investigations.unshift(x);save(d);json(s,x,201)},'POST /api/evidence':async(q,s)=>{const b=await body(q),d=state();if(d.evidence.find(x=>x.investigationId===b.investigationId&&x.url&&x.url===b.url))return json(s,{error:'That URL is already captured in this investigation.'},409);const x={id:id('evidence'),investigationId:b.investigationId,sourceType:b.sourceType||'Web',url:b.url||'',sourceName:b.sourceName||'',notes:b.notes||'',image:b.image||'',provenance:b.provenance||null,createdAt:new Date().toISOString()};x.analysis=analysisFor(x);d.evidence.unshift(x);d.leads.unshift({id:id('lead'),investigationId:x.investigationId,question:'What additional visual evidence would test this source?',why:'Metadata and source context do not establish visual relationships.',evidenceId:x.id,status:'New'});save(d);json(s,x,201)},'PATCH /api/leads':async(q,s)=>{const b=await body(q),d=state(),x=d.leads.find(x=>x.id===b.id);if(!x)return json(s,{error:'Lead not found'},404);x.status=b.status;save(d);json(s,x)}};
function json(s,d,c=200){const b=JSON.stringify(d);s.writeHead(c,{'Content-Type':'application/json','Content-Length':Buffer.byteLength(b)});s.end(b)}function body(q){return new Promise((ok,bad)=>{let x='';q.on('data',c=>{x+=c;if(x.length>8e6)q.destroy()});q.on('end',()=>{try{ok(x?JSON.parse(x):{})}catch{bad(Error('Invalid JSON'))}});q.on('error',bad)})}function staticFile(q,s,p){const rel=(p==='/'?'index.html':decodeURIComponent(p)).replace(/^\/+/,''),file=path.join(PUBLIC,rel);if(!file.startsWith(PUBLIC))return json(s,{error:'Not found'},404);fs.readFile(file,(e,d)=>e?json(s,{error:'Not found'},404):(s.writeHead(200,{'Content-Type':MIME[path.extname(file)]||'application/octet-stream'}),s.end(d)))}http.createServer(async(q,s)=>{try{const p=new URL(q.url,'http://x').pathname,h=routes[`${q.method} ${p}`];h?await h(q,s):staticFile(q,s,p)}catch(e){console.error(e);json(s,{error:'Server error'},500)}}).listen(PORT,()=>console.log(`Listening on port ${PORT}`));
